# Generated by Django 4.2.1 on 2023-07-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
    ]
